package com.eleven.boke.mapper;

import com.eleven.boke.pojo.Do.BokeArticleMessageDo;
import java.util.List;

public interface BokeArticleMessageDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_article_message
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_article_message
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    int insert(BokeArticleMessageDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_article_message
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    BokeArticleMessageDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_article_message
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    List<BokeArticleMessageDo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_article_message
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    int updateByPrimaryKey(BokeArticleMessageDo record);
}
