package com.eleven.boke.mapper;

import com.eleven.boke.pojo.Do.BokeArticleInfoDo;
import com.eleven.boke.pojo.query.ArticleListQuery;

import java.util.List;

public interface BokeArticleInfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_article_info
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_article_info
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    int insert(BokeArticleInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_article_info
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    BokeArticleInfoDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_article_info
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    List<BokeArticleInfoDo> selectAll();

    List<BokeArticleInfoDo> pageQuery(ArticleListQuery query);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_article_info
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    int updateByPrimaryKey(BokeArticleInfoDo record);
}
