package com.eleven.boke.mapper;

import com.eleven.boke.pojo.Do.BokeSysViewDo;
import java.util.List;

public interface BokeSysViewDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_sys_view
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    int deleteByPrimaryKey(String ip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_sys_view
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    int insert(BokeSysViewDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_sys_view
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    BokeSysViewDo selectByPrimaryKey(String ip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_sys_view
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    List<BokeSysViewDo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke_sys_view
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    int updateByPrimaryKey(BokeSysViewDo record);
}
