package com.eleven.boke.pojo.Do;

import java.util.Date;

public class BokeArticleMessageDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_message.id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_message.content
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_message.email
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_message.name
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private String name;

    private String createTime;

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_message.ip
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_message.is_effective
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Long isEffective;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_message.gmt_created
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_message.gmt_modified
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_message.id
     *
     * @return the value of boke_article_message.id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_message.id
     *
     * @param id the value for boke_article_message.id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_message.content
     *
     * @return the value of boke_article_message.content
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_message.content
     *
     * @param content the value for boke_article_message.content
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_message.email
     *
     * @return the value of boke_article_message.email
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_message.email
     *
     * @param email the value for boke_article_message.email
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_message.name
     *
     * @return the value of boke_article_message.name
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_message.name
     *
     * @param name the value for boke_article_message.name
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_message.ip
     *
     * @return the value of boke_article_message.ip
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_message.ip
     *
     * @param ip the value for boke_article_message.ip
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_message.is_effective
     *
     * @return the value of boke_article_message.is_effective
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Long getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_message.is_effective
     *
     * @param isEffective the value for boke_article_message.is_effective
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setIsEffective(Long isEffective) {
        this.isEffective = isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_message.gmt_created
     *
     * @return the value of boke_article_message.gmt_created
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_message.gmt_created
     *
     * @param gmtCreated the value for boke_article_message.gmt_created
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_message.gmt_modified
     *
     * @return the value of boke_article_message.gmt_modified
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_message.gmt_modified
     *
     * @param gmtModified the value for boke_article_message.gmt_modified
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}
