package com.eleven.boke.pojo.Do;

import java.util.Date;

public class BokeArticleInfoDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_info.id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_info.title
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_info.summary
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_info.is_top
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Long isTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_info.traffic
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Integer traffic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_info.message_id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Integer messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_info.picture
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_info.sort_id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Long sortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_info.gmt_created
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_info.gmt_modified
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_article_info.content
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_info.id
     *
     * @return the value of boke_article_info.id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_info.id
     *
     * @param id the value for boke_article_info.id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_info.title
     *
     * @return the value of boke_article_info.title
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_info.title
     *
     * @param title the value for boke_article_info.title
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_info.summary
     *
     * @return the value of boke_article_info.summary
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_info.summary
     *
     * @param summary the value for boke_article_info.summary
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_info.is_top
     *
     * @return the value of boke_article_info.is_top
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Long getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_info.is_top
     *
     * @param isTop the value for boke_article_info.is_top
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setIsTop(Long isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_info.traffic
     *
     * @return the value of boke_article_info.traffic
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Integer getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_info.traffic
     *
     * @param traffic the value for boke_article_info.traffic
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setTraffic(Integer traffic) {
        this.traffic = traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_info.message_id
     *
     * @return the value of boke_article_info.message_id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_info.message_id
     *
     * @param messageId the value for boke_article_info.message_id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_info.picture
     *
     * @return the value of boke_article_info.picture
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_info.picture
     *
     * @param picture the value for boke_article_info.picture
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_info.sort_id
     *
     * @return the value of boke_article_info.sort_id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Long getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_info.sort_id
     *
     * @param sortId the value for boke_article_info.sort_id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setSortId(Long sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_info.gmt_created
     *
     * @return the value of boke_article_info.gmt_created
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_info.gmt_created
     *
     * @param gmtCreated the value for boke_article_info.gmt_created
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_info.gmt_modified
     *
     * @return the value of boke_article_info.gmt_modified
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_info.gmt_modified
     *
     * @param gmtModified the value for boke_article_info.gmt_modified
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_article_info.content
     *
     * @return the value of boke_article_info.content
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_article_info.content
     *
     * @param content the value for boke_article_info.content
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }
}
