package com.eleven.boke.pojo.Do;

import java.util.Date;

public class BokeSysViewDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_sys_view.id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_sys_view.ip
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_sys_view.gmt_created
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke_sys_view.gmt_modified
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_sys_view.id
     *
     * @return the value of boke_sys_view.id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_sys_view.id
     *
     * @param id the value for boke_sys_view.id
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_sys_view.ip
     *
     * @return the value of boke_sys_view.ip
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_sys_view.ip
     *
     * @param ip the value for boke_sys_view.ip
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_sys_view.gmt_created
     *
     * @return the value of boke_sys_view.gmt_created
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_sys_view.gmt_created
     *
     * @param gmtCreated the value for boke_sys_view.gmt_created
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke_sys_view.gmt_modified
     *
     * @return the value of boke_sys_view.gmt_modified
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke_sys_view.gmt_modified
     *
     * @param gmtModified the value for boke_sys_view.gmt_modified
     *
     * @mbg.generated Wed Nov 18 11:04:38 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}
